//! Rules that keep the shared Clippy configuration in force.
//!
//! The root `clippy.toml` bans methods through `disallowed-methods`. Clippy
//! 1.98.1 uses that file only if no nearer one exists: it searches
//! `CLIPPY_CONF_DIR`, then `CARGO_MANIFEST_DIR`, and walks up to the first
//! directory holding `clippy.toml` or `.clippy.toml` (Clippy book,
//! "Configuring Clippy"; `clippy_config::lookup_conf_file`). All the bans share
//! one lint, `clippy::disallowed_methods`, in the `style` group. An allowance
//! of that lint, of `style`, of `clippy::all` or of `warnings` therefore turns
//! off every ban at once. Each rule rejects one of those routes:
//!
//! - a `clippy.toml` or `.clippy.toml` under `apps/` or `packages/`;
//! - an `allow` or `expect` of those lints wider than one statement: an inner
//!   attribute anywhere, or an outer attribute on a `mod`, `fn`, `impl` or
//!   `trait` item;
//! - an outer `allow` of those lints at any scope, which stays silent once the
//!   call it covered is gone, where `expect` fails;
//! - an `expect` of those lints without `reason = "..."`;
//! - a Cargo `[lints]` or `[workspace.lints]` table that allows or expects
//!   them;
//! - `CLIPPY_CONF_DIR`, `--cap-lints`, or a command-line allowance of those
//!   lints in mise, Cargo or workflow configuration, including the root's and
//!   any `.cargo/config` or `.cargo/config.toml` under `apps/` or `packages/`,
//!   and a `NAME=-A...` assignment inside a command;
//! - a root file that is missing, lacks a required ban, or has an entry
//!   without a reason.
//!
//! A reviewed call site is allowed individually with
//! `#[expect(clippy::disallowed_methods, reason = "...")]` on its statement.
//! The rules read text. They cannot see an allowance generated by a macro or
//! lint flags supplied from outside the repository.

use std::{collections::BTreeSet, fs, path::Path};

use anyhow::{Context, Result};
use toml::Value;

const CONFIG_NAMES: [&str; 2] = ["clippy.toml", ".clippy.toml"];
/// Lint names whose allowance switches off every configured ban: the lint,
/// its former name, its group, Clippy's default set and all warnings.
const SWITCHES: [&str; 5] = [
    "clippy::disallowed_methods",
    "clippy::disallowed_method",
    "clippy::style",
    "clippy::all",
    "warnings",
];
/// Every ban the first class check lands. Removing one is a reviewed change
/// to this list, not a silent edit of `clippy.toml`.
const REQUIRED_BANS: [&str; 9] = [
    "tracing::subscriber::set_default",
    "tracing::subscriber::with_default",
    "tracing::subscriber::set_global_default",
    "tracing::dispatcher::set_default",
    "tracing::dispatcher::with_default",
    "tracing::dispatcher::set_global_default",
    "tracing_subscriber::util::SubscriberInitExt::set_default",
    "tracing_subscriber::util::SubscriberInitExt::try_init",
    "tracing_subscriber::util::SubscriberInitExt::init",
];
/// Directories never scanned: build output and installed Node packages.
const SKIPPED: [&str; 2] = ["target", "node_modules"];

pub(super) fn check(root: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    root_configuration(root, errors)?;
    for category in ["apps", "packages"] {
        let directory = root.join(category);
        if directory.is_dir() {
            scan(root, &directory, errors)?;
        }
    }
    let mut manifests = vec![root.join("Cargo.toml")];
    let mut configurations = vec![
        root.join("mise.toml"),
        root.join(".cargo/config.toml"),
        root.join(".cargo/config"),
    ];
    for category in ["apps", "packages"] {
        let Ok(entries) = fs::read_dir(root.join(category)) else {
            continue;
        };
        for entry in entries {
            let entry = entry?;
            // A linked member may lead outside the repository; never read it.
            if !entry.file_type()?.is_dir() {
                continue;
            }
            let path = entry.path();
            manifests.push(path.join("Cargo.toml"));
            configurations.push(path.join("mise.toml"));
        }
    }
    if let Ok(entries) = fs::read_dir(root.join(".github/workflows")) {
        for entry in entries {
            configurations.push(entry?.path());
        }
    }
    manifests.sort();
    for manifest in manifests.iter().filter(|path| path.is_file()) {
        cargo_lints(root, manifest, errors)?;
    }
    configurations.sort();
    for configuration in configurations.iter().filter(|path| path.is_file()) {
        let text = fs::read_to_string(configuration)
            .with_context(|| format!("read {}", configuration.display()))?;
        command_line(&relative(root, configuration), &text, errors);
    }
    Ok(())
}

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn root_configuration(root: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    let path = root.join("clippy.toml");
    if !path.is_file() {
        errors.insert(
            "clippy.toml: the root Clippy configuration is missing; it holds the workspace's disallowed-methods bans".into(),
        );
        return Ok(());
    }
    let text = fs::read_to_string(&path).context("read clippy.toml")?;
    let config: Value = toml::from_str(&text).context("parse clippy.toml")?;
    let entries = config
        .get("disallowed-methods")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default();
    let mut banned = BTreeSet::new();
    for (index, entry) in entries.iter().enumerate() {
        let path = entry.get("path").and_then(Value::as_str);
        let reason = entry.get("reason").and_then(Value::as_str);
        match (path, reason) {
            (Some(path), Some(reason)) if !reason.trim().is_empty() => {
                banned.insert(path.to_owned());
            }
            _ => {
                errors.insert(format!(
                    "clippy.toml: disallowed-methods entry {} needs a `path` and a non-empty `reason` naming the safe alternative",
                    index + 1
                ));
                if let Some(path) = path.or_else(|| entry.as_str()) {
                    banned.insert(path.to_owned());
                }
            }
        }
    }
    for required in REQUIRED_BANS {
        if !banned.contains(required) {
            errors.insert(format!(
                "clippy.toml: disallowed-methods must ban {required}"
            ));
        }
    }
    Ok(())
}

fn scan(root: &Path, directory: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    let mut entries = fs::read_dir(directory)
        .with_context(|| format!("read {}", directory.display()))?
        .collect::<std::io::Result<Vec<_>>>()?;
    entries.sort_by_key(fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        // The entry's own type: a linked directory is never followed.
        let kind = entry.file_type()?;
        if kind.is_dir() {
            if !SKIPPED.contains(&name.as_ref()) {
                scan(root, &path, errors)?;
            }
            continue;
        }
        if CONFIG_NAMES.contains(&name.as_ref()) {
            errors.insert(format!(
                "{}: Clippy would use this file instead of the root clippy.toml and drop its bans; keep lint configuration in the root file",
                relative(root, &path)
            ));
        }
        // Cargo reads every `.cargo/config{,.toml}` from a task's working
        // directory up, so a package's or category's file applies to its tasks.
        let cargo_configuration = ["config", "config.toml"].contains(&name.as_ref())
            && path
                .parent()
                .and_then(Path::file_name)
                .is_some_and(|parent| parent == ".cargo");
        if kind.is_file() && cargo_configuration {
            let text =
                fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
            command_line(&relative(root, &path), &text, errors);
        }
        if kind.is_file() && path.extension().is_some_and(|extension| extension == "rs") {
            let text =
                fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
            for (line, attribute, fault) in rejected_attributes(&text) {
                let path = relative(root, &path);
                errors.insert(match fault {
                    Fault::Module => format!(
                        "{path}:{line}: `{attribute}` switches off every disallowed-methods ban for a whole crate or module; expect clippy::disallowed_methods on the reviewed statement instead"
                    ),
                    Fault::Item(item) => format!(
                        "{path}:{line}: `{attribute}` on the `{item}` item switches off every disallowed-methods ban for every statement in it; expect clippy::disallowed_methods on the reviewed statement instead"
                    ),
                    Fault::Allow => format!(
                        "{path}:{line}: `{attribute}` allows a disallowed-methods ban and stays silent once the call is gone; use `expect` with a reason on the reviewed statement instead"
                    ),
                    Fault::Unexplained => format!(
                        "{path}:{line}: `{attribute}` expects a disallowed-methods ban without a reason; add `reason = \"...\"` saying why the statement is safe"
                    ),
                });
            }
        }
    }
    Ok(())
}

fn switches(text: &str) -> bool {
    // Compare whole paths: `clippy::all` must not match `clippy::allow_...`.
    text.split(|character: char| !(character.is_alphanumeric() || "_:".contains(character)))
        .any(|word| SWITCHES.contains(&word))
}

/// Why an attribute that allows or expects a lint in [`SWITCHES`] is
/// rejected. An attribute with several faults reports the first listed here.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Fault {
    /// An inner attribute, or an outer one on a `mod`: a crate or module.
    Module,
    /// An outer attribute on a `fn`, `impl` or `trait` item.
    Item(&'static str),
    /// `allow`, which stays silent once the call it covered is gone.
    Allow,
    /// An `expect` without `reason = "..."`.
    Unexplained,
}

/// Each `allow(...)` or `expect(...)` group in an attribute that names a lint
/// in [`SWITCHES`], as its level and whether it gives a reason.
fn suppressions(attribute: &str) -> Vec<(&'static str, bool)> {
    let code: Vec<char> = attribute.chars().collect();
    let mut found = Vec::new();
    let mut index = 0;
    while index < code.len() {
        let word: String = code[index..]
            .iter()
            .take_while(|character| character.is_alphanumeric() || **character == '_')
            .collect();
        if word.is_empty() {
            index += 1;
            continue;
        }
        let preceded = index > 0 && (code[index - 1] == ':' || code[index - 1].is_alphanumeric());
        index += word.chars().count();
        let level = match word.as_str() {
            "allow" => "allow",
            "expect" => "expect",
            _ => continue,
        };
        let mut open = index;
        while code
            .get(open)
            .is_some_and(|character| character.is_whitespace())
        {
            open += 1;
        }
        if preceded || code.get(open) != Some(&'(') {
            continue;
        }
        let Some(close) = closing_parenthesis(&code, open) else {
            break;
        };
        let group: String = code[open + 1..close].iter().collect();
        if switches(&group) {
            found.push((level, explained(&group)));
        }
        index = close + 1;
    }
    found
}

/// Whether lint-attribute arguments carry a `reason = ...` key.
fn explained(arguments: &str) -> bool {
    arguments.match_indices("reason").any(|(at, key)| {
        let before = arguments[..at].chars().next_back();
        !before.is_some_and(|character| character.is_alphanumeric() || character == '_')
            && arguments[at + key.len()..].trim_start().starts_with('=')
    })
}

/// The index of the `)` that closes the `(` at `open`.
fn closing_parenthesis(code: &[char], open: usize) -> Option<usize> {
    let mut depth = 0_usize;
    for (offset, character) in code[open..].iter().enumerate() {
        match character {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 {
                    return Some(open + offset);
                }
            }
            _ => {}
        }
    }
    None
}

/// Attributes that allow or expect a lint in [`SWITCHES`] and are rejected,
/// with the line each starts on and why.
fn rejected_attributes(source: &str) -> Vec<(usize, String, Fault)> {
    let code: Vec<char> = code_only(source).chars().collect();
    let mut found = Vec::new();
    let mut index = 0;
    while index < code.len() {
        if code[index] != '#' {
            index += 1;
            continue;
        }
        let start = index;
        let mut cursor = index + 1;
        let inner = code.get(cursor) == Some(&'!');
        if inner {
            cursor += 1;
        }
        while code
            .get(cursor)
            .is_some_and(|character| character.is_whitespace())
        {
            cursor += 1;
        }
        if code.get(cursor) != Some(&'[') {
            index += 1;
            continue;
        }
        let Some(end) = closing(&code, cursor) else {
            break;
        };
        let attribute: String = code[start..=end].iter().collect();
        index = end + 1;
        let levels = suppressions(&attribute);
        if levels.is_empty() {
            continue;
        }
        let fault = if inner {
            Some(Fault::Module)
        } else {
            match annotated_item(&code, index) {
                Some("mod") => Some(Fault::Module),
                Some(item) => Some(Fault::Item(item)),
                None if levels.iter().any(|(level, _)| *level == "allow") => Some(Fault::Allow),
                None if levels.iter().any(|(_, reason)| !reason) => Some(Fault::Unexplained),
                None => None,
            }
        };
        if let Some(fault) = fault {
            let line = code[..start]
                .iter()
                .filter(|&&character| character == '\n')
                .count()
                + 1;
            found.push((
                line,
                attribute.split_whitespace().collect::<Vec<_>>().join(" "),
                fault,
            ));
        }
    }
    found
}

/// The index of the `]` that closes the `[` at `open`.
fn closing(code: &[char], open: usize) -> Option<usize> {
    let mut depth = 0_usize;
    for (offset, character) in code[open..].iter().enumerate() {
        match character {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(open + offset);
                }
            }
            _ => {}
        }
    }
    None
}

/// The kind of item after an outer attribute ending before `index`, past
/// any further outer attributes, a visibility and qualifiers, when it is one
/// whose attribute covers more than one statement: `mod`, `fn`, `impl` or
/// `trait`.
fn annotated_item(code: &[char], mut index: usize) -> Option<&'static str> {
    let skip_whitespace = |index: &mut usize| {
        while code
            .get(*index)
            .is_some_and(|character| character.is_whitespace())
        {
            *index += 1;
        }
    };
    loop {
        skip_whitespace(&mut index);
        if code.get(index) == Some(&'#') {
            let mut open = index + 1;
            skip_whitespace(&mut open);
            match (code.get(open), closing(code, open)) {
                (Some('['), Some(end)) => {
                    index = end + 1;
                    continue;
                }
                _ => return None,
            }
        }
        let word: String = code[index..]
            .iter()
            .take_while(|character| character.is_alphanumeric() || **character == '_')
            .collect();
        index += word.chars().count();
        match word.as_str() {
            "mod" => return Some("mod"),
            "fn" => return Some("fn"),
            "impl" => return Some("impl"),
            "trait" => return Some("trait"),
            "pub" => {
                skip_whitespace(&mut index);
                if code.get(index) == Some(&'(') {
                    index += code[index..]
                        .iter()
                        .position(|character| *character == ')')?
                        + 1;
                }
            }
            "const" | "async" | "unsafe" | "safe" | "default" | "auto" => {}
            "extern" => {
                // An ABI string: `extern "C" fn`.
                skip_whitespace(&mut index);
                if code.get(index) == Some(&'"') {
                    index += code[index + 1..]
                        .iter()
                        .position(|character| *character == '"')?
                        + 2;
                }
            }
            _ => return None,
        }
    }
}

/// Rust source with comments removed and string and character literal
/// contents blanked, so text inside them is never read as an attribute. Line
/// breaks are kept for line numbers.
fn code_only(source: &str) -> String {
    let characters: Vec<char> = source.chars().collect();
    let mut code = String::with_capacity(source.len());
    let mut index = 0;
    let blank = |code: &mut String, character: char| {
        code.push(if character == '\n' { '\n' } else { ' ' });
    };
    while index < characters.len() {
        let character = characters[index];
        let next = characters.get(index + 1).copied();
        if character == '/' && next == Some('/') {
            while index < characters.len() && characters[index] != '\n' {
                index += 1;
            }
            continue;
        }
        if character == '/' && next == Some('*') {
            let mut depth = 0_usize;
            while index < characters.len() {
                if characters[index] == '/' && characters.get(index + 1) == Some(&'*') {
                    depth += 1;
                    index += 2;
                    code.push_str("  ");
                } else if characters[index] == '*' && characters.get(index + 1) == Some(&'/') {
                    depth -= 1;
                    index += 2;
                    code.push_str("  ");
                    if depth == 0 {
                        break;
                    }
                } else {
                    blank(&mut code, characters[index]);
                    index += 1;
                }
            }
            continue;
        }
        // Raw strings: r"..", r#".."#, br".." and cr"..".
        let raw_start = match (character, next) {
            ('r', Some('"' | '#')) => Some(index + 1),
            ('b' | 'c', Some('r')) if matches!(characters.get(index + 2), Some('"' | '#')) => {
                Some(index + 2)
            }
            _ => None,
        };
        let identifier_before =
            index > 0 && (characters[index - 1].is_alphanumeric() || characters[index - 1] == '_');
        if let Some(start) = raw_start.filter(|_| !identifier_before) {
            let hashes = characters[start..]
                .iter()
                .take_while(|character| **character == '#')
                .count();
            if characters.get(start + hashes) == Some(&'"') {
                let terminator: Vec<char> = std::iter::once('"')
                    .chain(std::iter::repeat_n('#', hashes))
                    .collect();
                for &character in &characters[index..=start + hashes] {
                    code.push(character);
                }
                index = start + hashes + 1;
                while index < characters.len() && !characters[index..].starts_with(&terminator) {
                    blank(&mut code, characters[index]);
                    index += 1;
                }
                for &character in characters[index..].iter().take(terminator.len()) {
                    code.push(character);
                }
                index += terminator.len();
                continue;
            }
        }
        if character == '"' {
            code.push('"');
            index += 1;
            while index < characters.len() && characters[index] != '"' {
                if characters[index] == '\\' {
                    blank(&mut code, characters[index]);
                    index += 1;
                    if index >= characters.len() {
                        break;
                    }
                }
                blank(&mut code, characters[index]);
                index += 1;
            }
            code.push('"');
            index += 1;
            continue;
        }
        if character == '\'' {
            // A character literal, not a lifetime: `'\..'` or `'x'`.
            // An escape's first character may itself be a quote: `'\''`.
            let end = if next == Some('\\') {
                characters
                    .get(index + 3..)
                    .and_then(|rest| rest.iter().position(|character| *character == '\''))
                    .map(|offset| index + 3 + offset)
            } else if characters.get(index + 2) == Some(&'\'') {
                Some(index + 2)
            } else {
                None
            };
            if let Some(end) = end {
                code.push_str(&" ".repeat(end + 1 - index));
                index = end + 1;
                continue;
            }
        }
        code.push(character);
        index += 1;
    }
    code
}

fn level_suppresses(level: &Value) -> bool {
    let level = level
        .as_str()
        .or_else(|| level.get("level").and_then(Value::as_str));
    matches!(level, Some("allow" | "expect"))
}

fn cargo_lints(root: &Path, manifest: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    let text =
        fs::read_to_string(manifest).with_context(|| format!("read {}", manifest.display()))?;
    let value: Value =
        toml::from_str(&text).with_context(|| format!("parse {}", manifest.display()))?;
    let name = relative(root, manifest);
    let tables = [
        ("lints", value.get("lints")),
        (
            "workspace.lints",
            value
                .get("workspace")
                .and_then(|workspace| workspace.get("lints")),
        ),
    ];
    for (table, lints) in tables {
        let Some(lints) = lints else { continue };
        for (tool, prefix) in [("clippy", "clippy::"), ("rust", "")] {
            for (lint, level) in lints
                .get(tool)
                .and_then(Value::as_table)
                .into_iter()
                .flatten()
            {
                let qualified = format!("{prefix}{}", lint.replace('-', "_"));
                if SWITCHES.contains(&qualified.as_str()) && level_suppresses(level) {
                    errors.insert(format!(
                        "{name}: [{table}.{tool}] {lint} switches off every disallowed-methods ban; expect clippy::disallowed_methods on the reviewed statement instead"
                    ));
                }
            }
        }
    }
    Ok(())
}

/// `CLIPPY_CONF_DIR`, `--cap-lints` and command-line allowances of a lint in
/// [`SWITCHES`] in mise, Cargo or workflow configuration text.
fn command_line(name: &str, text: &str, errors: &mut BTreeSet<String>) {
    if text.contains("CLIPPY_CONF_DIR") {
        errors.insert(format!(
            "{name}: sets CLIPPY_CONF_DIR, which makes Clippy read another configuration instead of the root clippy.toml"
        ));
    }
    if text.contains("--cap-lints") {
        errors.insert(format!(
            "{name}: passes --cap-lints, which lowers every disallowed-methods ban"
        ));
    }
    let words: Vec<&str> = text
        // `=` too: `RUSTFLAGS=-Aclippy::style cargo clippy` and `--allow=warnings`.
        .split(|character: char| character.is_whitespace() || "\"'`,[]{}=".contains(character))
        .filter(|word| !word.is_empty())
        .collect();
    for (index, word) in words.iter().enumerate() {
        let lint = match *word {
            "-A" | "--allow" | "--expect" => words.get(index + 1).copied(),
            _ => word.strip_prefix("-A").filter(|lint| !lint.is_empty()),
        };
        if let Some(lint) = lint.map(|lint| lint.replace('-', "_"))
            && SWITCHES.contains(&lint.as_str())
        {
            errors.insert(format!(
                "{name}: allows {lint} on the command line, which switches off every disallowed-methods ban"
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn allowances(source: &str) -> Vec<usize> {
        rejected_attributes(source)
            .into_iter()
            .map(|(line, _, _)| line)
            .collect()
    }

    #[test]
    fn crate_and_module_allowances_are_found_and_statement_expectations_are_not() {
        let source = "#![allow(clippy::disallowed_methods)]\n\
            #![cfg_attr(test, expect(clippy::style, reason = \"x\"))]\n\
            #[allow(clippy::all)]\n#[cfg(test)]\npub(crate) mod tests;\n\
            #[expect(warnings)]\npub mod inline {}\n\
            #[allow(clippy::disallowed_methods)]\nfn item() {}\n\
            fn body() {\n    #[expect(clippy::disallowed_methods, reason = \"x\")]\n    call();\n}\n\
            #![warn(clippy::disallowed_methods)]\n#![allow(clippy::allow_attributes)]\n\
            #![allow(dead_code)]\n#[allow(clippy::disallowed_method)] mod old;\n";
        assert_eq!(allowances(source), [1, 2, 3, 6, 8, 17]);
    }

    fn faults(source: &str) -> Vec<(usize, Fault)> {
        rejected_attributes(source)
            .into_iter()
            .map(|(line, _, fault)| (line, fault))
            .collect()
    }

    #[test]
    fn allowances_wider_than_a_statement_outer_allows_and_unexplained_expectations_are_found() {
        // The review's bypass: every caller of this wrapper escapes the ban.
        let wrapper = "#[allow(clippy::disallowed_methods)]\n\
            fn capture<T>(subscriber: S, f: impl FnOnce() -> T) -> T {\n\
                tracing::subscriber::with_default(subscriber, f)\n\
            }\n";
        assert_eq!(faults(wrapper), [(1, Fault::Item("fn"))]);
        let reviewed = "#[expect(clippy::disallowed_methods, reason = \"x\")]\n";
        for (item, kind) in [
            ("fn wrapper() {}", "fn"),
            ("pub(crate) async fn wrapper() {}", "fn"),
            ("const unsafe fn wrapper() {}", "fn"),
            ("pub extern \"C\" fn wrapper() {}", "fn"),
            ("impl Capture {}", "impl"),
            ("unsafe impl Send for Capture {}", "impl"),
            ("default impl<T> Capture for T {}", "impl"),
            ("#[cfg(test)]\ntrait Capture {}", "trait"),
            ("pub unsafe auto trait Capture {}", "trait"),
        ] {
            assert_eq!(
                faults(&format!("{reviewed}{item}")),
                [(1, Fault::Item(kind))],
                "{item}"
            );
        }
        for statement in [
            "call();",
            "let value = call();",
            "const LIMIT: u8 = 1;",
            "unsafe { call() }",
            "async move { call() }",
            "extern crate tracing;",
            "extern \"C\" { fn call(); }",
            "pub struct Capture;",
        ] {
            assert!(
                faults(&format!("{reviewed}{statement}")).is_empty(),
                "{statement}"
            );
        }
        let source = "fn body() {\n\
            #[allow(clippy::disallowed_methods, reason = \"x\")]\n    call();\n\
            #[expect(clippy::disallowed_methods)]\n    call();\n\
            #[cfg_attr(test, allow(clippy::all))]\n    call();\n\
            #[expect(warnings, reasons = \"x\")]\n    call();\n\
            #[cfg_attr(test, allow(dead_code), expect(clippy::style, reason = \"x\"))]\n    call();\n\
            #[allow(dead_code, reason = \"x\")] #[expect(clippy::disallowed_methods, reason = \"x\")]\n    call();\n\
            #[allow(clippy::allow_attributes)] #[lint::allow(clippy::all)]\n    call();\n\
            }\n";
        assert_eq!(
            faults(source),
            [
                (2, Fault::Allow),
                (4, Fault::Unexplained),
                (6, Fault::Allow),
                (8, Fault::Unexplained),
            ]
        );
        assert!(suppressions("#[expect(clippy::all, reason = \"x\"").is_empty());
        assert!(faults("#[expect(clippy::all, reason = \"x\")] pub extern \"C").is_empty());
        assert!(faults("#[expect(clippy::all, reason = \"x\")] pub(crate").is_empty());
    }

    #[test]
    fn comments_strings_and_characters_are_not_code() {
        let source = "// #![allow(clippy::disallowed_methods)]\n\
            /* #![allow(clippy::all)] /* nested */ #![allow(warnings)] */\n\
            const A: &str = \"#![allow(clippy::disallowed_methods)] \\\" #![allow(warnings)]\";\n\
            const B: &str = r#\"#![allow(clippy::style)] \"# ;\n\
            const C: &[u8] = br\"#![allow(clippy::all)]\";\n\
            const D: char = '\"'; const E: char = '\\''; fn f<'a>(x: &'a str) {}\n\
            #![allow(clippy::style)]\n";
        assert_eq!(allowances(source), [7]);
    }

    #[test]
    fn malformed_attributes_end_the_item_scan_but_an_outer_allow_is_still_found() {
        assert!(allowances("#![allow(clippy::all)").is_empty());
        assert!(allowances("# not an attribute\n#![allow(dead_code)]").is_empty());
        // An outer `allow` is rejected wherever the item scan stops ...
        assert_eq!(allowances("#[allow(clippy::all)] #"), [1]);
        assert_eq!(allowances("#[allow(clippy::all)] pub(crate"), [1]);
        assert_eq!(allowances("#[allow(clippy::all)] #[cfg(test)"), [1]);
        assert_eq!(allowances("#[allow(clippy::all)] fn f() {}"), [1]);
        assert_eq!(allowances("#[allow(clippy::all)] #[cfg(test)] mod m;"), [1]);
        // ... and a reasoned `expect` is not, unless an item follows.
        let reviewed = "#[expect(clippy::all, reason = \"x\")]";
        assert!(allowances(&format!("{reviewed} #")).is_empty());
        assert!(allowances(&format!("{reviewed} pub(crate")).is_empty());
        assert!(allowances(&format!("{reviewed} #[cfg(test)")).is_empty());
        assert_eq!(allowances(&format!("{reviewed} fn f() {{}}")), [1]);
        assert_eq!(allowances(&format!("{reviewed} #[cfg(test)] mod m;")), [1]);
    }

    #[test]
    fn command_line_switches_are_found_in_every_spelling() {
        let mut errors = BTreeSet::new();
        command_line(
            "mise.toml",
            "run = \"cargo clippy -- -D warnings -A clippy::disallowed-methods\"\n\
             RUSTFLAGS = '-Aclippy::style --allow=warnings'\n\
             args: [--allow, clippy::all]\n\
             CLIPPY_CONF_DIR = \"x\"\nflags = \"--cap-lints allow\"\n",
            &mut errors,
        );
        let errors: Vec<_> = errors.into_iter().collect();
        assert_eq!(errors.len(), 6, "{errors:?}");
        for lint in [
            "clippy::disallowed_methods",
            "clippy::style",
            "warnings",
            "clippy::all",
        ] {
            assert!(
                errors
                    .iter()
                    .any(|error| error.contains(&format!("allows {lint}")))
            );
        }
        let mut errors = BTreeSet::new();
        command_line(
            "mise.toml",
            "run = \"cargo clippy -- -D warnings -A dead_code -A\"\nfile = \"-A\"",
            &mut errors,
        );
        assert!(errors.is_empty(), "{errors:?}");
        // A command word is split at `=` as well: an environment assignment
        // inside a command, and `--expect=`.
        for (text, lint) in [
            (
                "run = \"RUSTFLAGS=-Aclippy::disallowed_methods cargo clippy\"",
                "clippy::disallowed_methods",
            ),
            (
                "run = 'cargo clippy -- --expect=clippy::style'",
                "clippy::style",
            ),
            ("env = \"RUSTFLAGS=--allow=warnings\"", "warnings"),
        ] {
            let mut errors = BTreeSet::new();
            command_line("mise.toml", text, &mut errors);
            assert_eq!(
                errors.into_iter().collect::<Vec<_>>(),
                [format!(
                    "mise.toml: allows {lint} on the command line, which switches off every disallowed-methods ban"
                )],
                "{text}"
            );
        }
    }

    #[test]
    fn cargo_lint_levels_that_allow_or_expect_are_rejected() {
        let levels = |text: &str| {
            let value: Value = toml::from_str(text).unwrap();
            level_suppresses(&value["x"])
        };
        assert!(levels("x = \"allow\""));
        assert!(levels("x = { level = \"expect\", priority = 1 }"));
        assert!(!levels("x = \"deny\""));
        assert!(!levels("x = { priority = 1 }"));
        assert!(switches("clippy::all"));
        assert!(!switches("clippy::allow_attributes"));
        assert_eq!(
            relative(Path::new("/root"), Path::new("/elsewhere/a")),
            "/elsewhere/a"
        );
    }
}
