//! Rules that keep the shared Clippy configuration in force.
//!
//! The root `clippy.toml` bans methods through `disallowed-methods`. Clippy
//! 1.98.1 uses that file only if no nearer one exists: it searches
//! `CLIPPY_CONF_DIR`, then `CARGO_MANIFEST_DIR`, and walks up to the first
//! directory holding `clippy.toml` or `.clippy.toml` (Clippy book,
//! "Configuring Clippy"; `clippy_config::lookup_conf_file`). All the bans share
//! one lint, `clippy::disallowed_methods`, in the `style` group. An allowance
//! of that lint, of `style`, of `clippy::all` or of `warnings` therefore turns
//! off every ban at once. Each rule rejects one of those routes:
//!
//! - a `clippy.toml` or `.clippy.toml` under `apps/` or `packages/`;
//! - a crate- or module-level `allow` or `expect` of those lints: an inner
//!   attribute anywhere, or an outer attribute on a `mod` item;
//! - a Cargo `[lints]` or `[workspace.lints]` table that allows or expects
//!   them;
//! - `CLIPPY_CONF_DIR`, `--cap-lints`, or a command-line allowance of those
//!   lints in mise, Cargo or workflow configuration;
//! - a root file that is missing, lacks a required ban, or has an entry
//!   without a reason.
//!
//! A reviewed call site is allowed individually with
//! `#[expect(clippy::disallowed_methods, reason = "...")]` on its statement.
//! The rules read text. They cannot see an allowance generated by a macro or
//! lint flags supplied from outside the repository.

use std::{collections::BTreeSet, fs, path::Path};

use anyhow::{Context, Result};
use toml::Value;

const CONFIG_NAMES: [&str; 2] = ["clippy.toml", ".clippy.toml"];
/// Lint names whose allowance switches off every configured ban: the lint,
/// its former name, its group, Clippy's default set and all warnings.
const SWITCHES: [&str; 5] = [
    "clippy::disallowed_methods",
    "clippy::disallowed_method",
    "clippy::style",
    "clippy::all",
    "warnings",
];
/// Every ban the first class check lands. Removing one is a reviewed change
/// to this list, not a silent edit of `clippy.toml`.
const REQUIRED_BANS: [&str; 9] = [
    "tracing::subscriber::set_default",
    "tracing::subscriber::with_default",
    "tracing::subscriber::set_global_default",
    "tracing::dispatcher::set_default",
    "tracing::dispatcher::with_default",
    "tracing::dispatcher::set_global_default",
    "tracing_subscriber::util::SubscriberInitExt::set_default",
    "tracing_subscriber::util::SubscriberInitExt::try_init",
    "tracing_subscriber::util::SubscriberInitExt::init",
];
/// Directories never scanned: build output and installed Node packages.
const SKIPPED: [&str; 2] = ["target", "node_modules"];

pub(super) fn check(root: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    root_configuration(root, errors)?;
    for category in ["apps", "packages"] {
        let directory = root.join(category);
        if directory.is_dir() {
            scan(root, &directory, errors)?;
        }
    }
    let mut manifests = vec![root.join("Cargo.toml")];
    let mut configurations = vec![
        root.join("mise.toml"),
        root.join(".cargo/config.toml"),
        root.join(".cargo/config"),
    ];
    for category in ["apps", "packages"] {
        let Ok(entries) = fs::read_dir(root.join(category)) else {
            continue;
        };
        for entry in entries {
            let entry = entry?;
            // A linked member may lead outside the repository; never read it.
            if !entry.file_type()?.is_dir() {
                continue;
            }
            let path = entry.path();
            manifests.push(path.join("Cargo.toml"));
            configurations.push(path.join("mise.toml"));
        }
    }
    if let Ok(entries) = fs::read_dir(root.join(".github/workflows")) {
        for entry in entries {
            configurations.push(entry?.path());
        }
    }
    manifests.sort();
    for manifest in manifests.iter().filter(|path| path.is_file()) {
        cargo_lints(root, manifest, errors)?;
    }
    configurations.sort();
    for configuration in configurations.iter().filter(|path| path.is_file()) {
        let text = fs::read_to_string(configuration)
            .with_context(|| format!("read {}", configuration.display()))?;
        command_line(&relative(root, configuration), &text, errors);
    }
    Ok(())
}

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn root_configuration(root: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    let path = root.join("clippy.toml");
    if !path.is_file() {
        errors.insert(
            "clippy.toml: the root Clippy configuration is missing; it holds the workspace's disallowed-methods bans".into(),
        );
        return Ok(());
    }
    let text = fs::read_to_string(&path).context("read clippy.toml")?;
    let config: Value = toml::from_str(&text).context("parse clippy.toml")?;
    let entries = config
        .get("disallowed-methods")
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .unwrap_or_default();
    let mut banned = BTreeSet::new();
    for (index, entry) in entries.iter().enumerate() {
        let path = entry.get("path").and_then(Value::as_str);
        let reason = entry.get("reason").and_then(Value::as_str);
        match (path, reason) {
            (Some(path), Some(reason)) if !reason.trim().is_empty() => {
                banned.insert(path.to_owned());
            }
            _ => {
                errors.insert(format!(
                    "clippy.toml: disallowed-methods entry {} needs a `path` and a non-empty `reason` naming the safe alternative",
                    index + 1
                ));
                if let Some(path) = path.or_else(|| entry.as_str()) {
                    banned.insert(path.to_owned());
                }
            }
        }
    }
    for required in REQUIRED_BANS {
        if !banned.contains(required) {
            errors.insert(format!(
                "clippy.toml: disallowed-methods must ban {required}"
            ));
        }
    }
    Ok(())
}

fn scan(root: &Path, directory: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    let mut entries = fs::read_dir(directory)
        .with_context(|| format!("read {}", directory.display()))?
        .collect::<std::io::Result<Vec<_>>>()?;
    entries.sort_by_key(fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        // The entry's own type: a linked directory is never followed.
        let kind = entry.file_type()?;
        if kind.is_dir() {
            if !SKIPPED.contains(&name.as_ref()) {
                scan(root, &path, errors)?;
            }
            continue;
        }
        if CONFIG_NAMES.contains(&name.as_ref()) {
            errors.insert(format!(
                "{}: Clippy would use this file instead of the root clippy.toml and drop its bans; keep lint configuration in the root file",
                relative(root, &path)
            ));
        }
        if kind.is_file() && path.extension().is_some_and(|extension| extension == "rs") {
            let text =
                fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
            for (line, attribute) in broad_allowances(&text) {
                errors.insert(format!(
                    "{}:{line}: `{attribute}` switches off every disallowed-methods ban for a whole crate or module; expect clippy::disallowed_methods on the reviewed statement instead",
                    relative(root, &path)
                ));
            }
        }
    }
    Ok(())
}

fn switches(text: &str) -> bool {
    // Compare whole paths: `clippy::all` must not match `clippy::allow_...`.
    text.split(|character: char| !(character.is_alphanumeric() || "_:".contains(character)))
        .any(|word| SWITCHES.contains(&word))
}

fn suppresses(attribute: &str) -> bool {
    let words: Vec<&str> = attribute
        .split(|character: char| !(character.is_alphanumeric() || character == '_'))
        .collect();
    (words.contains(&"allow") || words.contains(&"expect")) && switches(attribute)
}

/// Inner attributes, and outer attributes on a `mod` item, that allow or
/// expect a lint in [`SWITCHES`], with the line each starts on.
fn broad_allowances(source: &str) -> Vec<(usize, String)> {
    let code: Vec<char> = code_only(source).chars().collect();
    let mut found = Vec::new();
    let mut index = 0;
    while index < code.len() {
        if code[index] != '#' {
            index += 1;
            continue;
        }
        let start = index;
        let mut cursor = index + 1;
        let inner = code.get(cursor) == Some(&'!');
        if inner {
            cursor += 1;
        }
        while code
            .get(cursor)
            .is_some_and(|character| character.is_whitespace())
        {
            cursor += 1;
        }
        if code.get(cursor) != Some(&'[') {
            index += 1;
            continue;
        }
        let Some(end) = closing(&code, cursor) else {
            break;
        };
        let attribute: String = code[start..=end].iter().collect();
        index = end + 1;
        if !suppresses(&attribute) {
            continue;
        }
        if inner || annotates_module(&code, index) {
            let line = code[..start]
                .iter()
                .filter(|&&character| character == '\n')
                .count()
                + 1;
            found.push((
                line,
                attribute.split_whitespace().collect::<Vec<_>>().join(" "),
            ));
        }
    }
    found
}

/// The index of the `]` that closes the `[` at `open`.
fn closing(code: &[char], open: usize) -> Option<usize> {
    let mut depth = 0_usize;
    for (offset, character) in code[open..].iter().enumerate() {
        match character {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(open + offset);
                }
            }
            _ => {}
        }
    }
    None
}

/// Whether the item after an outer attribute ending before `index` is a
/// module, past any further outer attributes and a visibility.
fn annotates_module(code: &[char], mut index: usize) -> bool {
    loop {
        while code
            .get(index)
            .is_some_and(|character| character.is_whitespace())
        {
            index += 1;
        }
        if code.get(index) == Some(&'#') {
            let mut open = index + 1;
            while code
                .get(open)
                .is_some_and(|character| character.is_whitespace())
            {
                open += 1;
            }
            match (code.get(open), closing(code, open)) {
                (Some('['), Some(end)) => {
                    index = end + 1;
                    continue;
                }
                _ => return false,
            }
        }
        let word: String = code[index..]
            .iter()
            .take_while(|character| character.is_alphanumeric() || **character == '_')
            .collect();
        match word.as_str() {
            "mod" => return true,
            "pub" => {
                index += word.len();
                while code
                    .get(index)
                    .is_some_and(|character| character.is_whitespace())
                {
                    index += 1;
                }
                if code.get(index) == Some(&'(') {
                    match code[index..].iter().position(|character| *character == ')') {
                        Some(offset) => index += offset + 1,
                        None => return false,
                    }
                }
            }
            _ => return false,
        }
    }
}

/// Rust source with comments removed and string and character literal
/// contents blanked, so text inside them is never read as an attribute. Line
/// breaks are kept for line numbers.
fn code_only(source: &str) -> String {
    let characters: Vec<char> = source.chars().collect();
    let mut code = String::with_capacity(source.len());
    let mut index = 0;
    let blank = |code: &mut String, character: char| {
        code.push(if character == '\n' { '\n' } else { ' ' });
    };
    while index < characters.len() {
        let character = characters[index];
        let next = characters.get(index + 1).copied();
        if character == '/' && next == Some('/') {
            while index < characters.len() && characters[index] != '\n' {
                index += 1;
            }
            continue;
        }
        if character == '/' && next == Some('*') {
            let mut depth = 0_usize;
            while index < characters.len() {
                if characters[index] == '/' && characters.get(index + 1) == Some(&'*') {
                    depth += 1;
                    index += 2;
                    code.push_str("  ");
                } else if characters[index] == '*' && characters.get(index + 1) == Some(&'/') {
                    depth -= 1;
                    index += 2;
                    code.push_str("  ");
                    if depth == 0 {
                        break;
                    }
                } else {
                    blank(&mut code, characters[index]);
                    index += 1;
                }
            }
            continue;
        }
        // Raw strings: r"..", r#".."#, br".." and cr"..".
        let raw_start = match (character, next) {
            ('r', Some('"' | '#')) => Some(index + 1),
            ('b' | 'c', Some('r')) if matches!(characters.get(index + 2), Some('"' | '#')) => {
                Some(index + 2)
            }
            _ => None,
        };
        let identifier_before =
            index > 0 && (characters[index - 1].is_alphanumeric() || characters[index - 1] == '_');
        if let Some(start) = raw_start.filter(|_| !identifier_before) {
            let hashes = characters[start..]
                .iter()
                .take_while(|character| **character == '#')
                .count();
            if characters.get(start + hashes) == Some(&'"') {
                let terminator: Vec<char> = std::iter::once('"')
                    .chain(std::iter::repeat_n('#', hashes))
                    .collect();
                for &character in &characters[index..=start + hashes] {
                    code.push(character);
                }
                index = start + hashes + 1;
                while index < characters.len() && !characters[index..].starts_with(&terminator) {
                    blank(&mut code, characters[index]);
                    index += 1;
                }
                for &character in characters[index..].iter().take(terminator.len()) {
                    code.push(character);
                }
                index += terminator.len();
                continue;
            }
        }
        if character == '"' {
            code.push('"');
            index += 1;
            while index < characters.len() && characters[index] != '"' {
                if characters[index] == '\\' {
                    blank(&mut code, characters[index]);
                    index += 1;
                    if index >= characters.len() {
                        break;
                    }
                }
                blank(&mut code, characters[index]);
                index += 1;
            }
            code.push('"');
            index += 1;
            continue;
        }
        if character == '\'' {
            // A character literal, not a lifetime: `'\..'` or `'x'`.
            // An escape's first character may itself be a quote: `'\''`.
            let end = if next == Some('\\') {
                characters
                    .get(index + 3..)
                    .and_then(|rest| rest.iter().position(|character| *character == '\''))
                    .map(|offset| index + 3 + offset)
            } else if characters.get(index + 2) == Some(&'\'') {
                Some(index + 2)
            } else {
                None
            };
            if let Some(end) = end {
                code.push_str(&" ".repeat(end + 1 - index));
                index = end + 1;
                continue;
            }
        }
        code.push(character);
        index += 1;
    }
    code
}

fn level_suppresses(level: &Value) -> bool {
    let level = level
        .as_str()
        .or_else(|| level.get("level").and_then(Value::as_str));
    matches!(level, Some("allow" | "expect"))
}

fn cargo_lints(root: &Path, manifest: &Path, errors: &mut BTreeSet<String>) -> Result<()> {
    let text =
        fs::read_to_string(manifest).with_context(|| format!("read {}", manifest.display()))?;
    let value: Value =
        toml::from_str(&text).with_context(|| format!("parse {}", manifest.display()))?;
    let name = relative(root, manifest);
    let tables = [
        ("lints", value.get("lints")),
        (
            "workspace.lints",
            value
                .get("workspace")
                .and_then(|workspace| workspace.get("lints")),
        ),
    ];
    for (table, lints) in tables {
        let Some(lints) = lints else { continue };
        for (tool, prefix) in [("clippy", "clippy::"), ("rust", "")] {
            for (lint, level) in lints
                .get(tool)
                .and_then(Value::as_table)
                .into_iter()
                .flatten()
            {
                let qualified = format!("{prefix}{}", lint.replace('-', "_"));
                if SWITCHES.contains(&qualified.as_str()) && level_suppresses(level) {
                    errors.insert(format!(
                        "{name}: [{table}.{tool}] {lint} switches off every disallowed-methods ban; expect clippy::disallowed_methods on the reviewed statement instead"
                    ));
                }
            }
        }
    }
    Ok(())
}

/// `CLIPPY_CONF_DIR`, `--cap-lints` and command-line allowances of a lint in
/// [`SWITCHES`] in mise, Cargo or workflow configuration text.
fn command_line(name: &str, text: &str, errors: &mut BTreeSet<String>) {
    if text.contains("CLIPPY_CONF_DIR") {
        errors.insert(format!(
            "{name}: sets CLIPPY_CONF_DIR, which makes Clippy read another configuration instead of the root clippy.toml"
        ));
    }
    if text.contains("--cap-lints") {
        errors.insert(format!(
            "{name}: passes --cap-lints, which lowers every disallowed-methods ban"
        ));
    }
    let words: Vec<&str> = text
        .split(|character: char| character.is_whitespace() || "\"'`,[]{}".contains(character))
        .filter(|word| !word.is_empty())
        .collect();
    for (index, word) in words.iter().enumerate() {
        let lint = match *word {
            "-A" | "--allow" | "--expect" => words.get(index + 1).copied(),
            _ => word
                .strip_prefix("--allow=")
                .or_else(|| word.strip_prefix("-A"))
                .filter(|lint| !lint.is_empty()),
        };
        if let Some(lint) = lint.map(|lint| lint.replace('-', "_"))
            && SWITCHES.contains(&lint.as_str())
        {
            errors.insert(format!(
                "{name}: allows {lint} on the command line, which switches off every disallowed-methods ban"
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn allowances(source: &str) -> Vec<usize> {
        broad_allowances(source)
            .into_iter()
            .map(|(line, _)| line)
            .collect()
    }

    #[test]
    fn crate_and_module_allowances_are_found_and_statement_expectations_are_not() {
        let source = "#![allow(clippy::disallowed_methods)]\n\
            #![cfg_attr(test, expect(clippy::style, reason = \"x\"))]\n\
            #[allow(clippy::all)]\n#[cfg(test)]\npub(crate) mod tests;\n\
            #[expect(warnings)]\npub mod inline {}\n\
            #[allow(clippy::disallowed_methods)]\nfn item() {}\n\
            fn body() {\n    #[expect(clippy::disallowed_methods, reason = \"x\")]\n    call();\n}\n\
            #![warn(clippy::disallowed_methods)]\n#![allow(clippy::allow_attributes)]\n\
            #![allow(dead_code)]\n#[allow(clippy::disallowed_method)] mod old;\n";
        assert_eq!(allowances(source), [1, 2, 3, 6, 17]);
    }

    #[test]
    fn comments_strings_and_characters_are_not_code() {
        let source = "// #![allow(clippy::disallowed_methods)]\n\
            /* #![allow(clippy::all)] /* nested */ #![allow(warnings)] */\n\
            const A: &str = \"#![allow(clippy::disallowed_methods)] \\\" #![allow(warnings)]\";\n\
            const B: &str = r#\"#![allow(clippy::style)] \"# ;\n\
            const C: &[u8] = br\"#![allow(clippy::all)]\";\n\
            const D: char = '\"'; const E: char = '\\''; fn f<'a>(x: &'a str) {}\n\
            #![allow(clippy::style)]\n";
        assert_eq!(allowances(source), [7]);
    }

    #[test]
    fn malformed_attributes_end_the_scan_without_a_finding() {
        assert!(allowances("#![allow(clippy::all)").is_empty());
        assert!(allowances("# not an attribute\n#![allow(dead_code)]").is_empty());
        assert!(allowances("#[allow(clippy::all)] #").is_empty());
        assert!(allowances("#[allow(clippy::all)] pub(crate").is_empty());
        assert!(allowances("#[allow(clippy::all)] #[cfg(test)").is_empty());
        assert!(allowances("#[allow(clippy::all)] fn f() {}").is_empty());
        assert_eq!(allowances("#[allow(clippy::all)] #[cfg(test)] mod m;"), [1]);
    }

    #[test]
    fn command_line_switches_are_found_in_every_spelling() {
        let mut errors = BTreeSet::new();
        command_line(
            "mise.toml",
            "run = \"cargo clippy -- -D warnings -A clippy::disallowed-methods\"\n\
             RUSTFLAGS = '-Aclippy::style --allow=warnings'\n\
             args: [--allow, clippy::all]\n\
             CLIPPY_CONF_DIR = \"x\"\nflags = \"--cap-lints allow\"\n",
            &mut errors,
        );
        let errors: Vec<_> = errors.into_iter().collect();
        assert_eq!(errors.len(), 6, "{errors:?}");
        for lint in [
            "clippy::disallowed_methods",
            "clippy::style",
            "warnings",
            "clippy::all",
        ] {
            assert!(
                errors
                    .iter()
                    .any(|error| error.contains(&format!("allows {lint}")))
            );
        }
        let mut errors = BTreeSet::new();
        command_line(
            "mise.toml",
            "run = \"cargo clippy -- -D warnings -A dead_code -A\"\nfile = \"-A\"",
            &mut errors,
        );
        assert!(errors.is_empty(), "{errors:?}");
    }

    #[test]
    fn cargo_lint_levels_that_allow_or_expect_are_rejected() {
        let levels = |text: &str| {
            let value: Value = toml::from_str(text).unwrap();
            level_suppresses(&value["x"])
        };
        assert!(levels("x = \"allow\""));
        assert!(levels("x = { level = \"expect\", priority = 1 }"));
        assert!(!levels("x = \"deny\""));
        assert!(!levels("x = { priority = 1 }"));
        assert!(switches("clippy::all"));
        assert!(!switches("clippy::allow_attributes"));
        assert_eq!(
            relative(Path::new("/root"), Path::new("/elsewhere/a")),
            "/elsewhere/a"
        );
    }
}
